before_script:
  - npm install

jshint:
  script:
    - grunt jshint
  tags:
    - node
    - grunt
    - jshint

mocha:
  script:
    - grunt mochaTest
  tags:
    - node
    - grunt
    - chai
    - sinon
    - mocha
