before_script:
  - npm install

jshint:
  script:
    - grunt jshint
  tags:
    - node
    - grunt
    - gyp

jasmine_nodejs:
  script:
    - grunt jasmine_nodejs
  tags:
    - node
    - grunt
    - gyp
