unittest:
  script:
    - pip install --quiet -r requirements.txt
    - ./mc_tests.sh
  tags:
    - python3

sample-pipeline:
  script:
    - pip install --quiet -r requirements.txt
    - ./mc_sample-pipeline.sh
  tags:
    - python3
  only:
    - master

sample-api:
  script:
    - pip install --quiet -r requirements.txt
    - ./mc_sample-api.sh
  tags:
    - python3
  only:
    - master

docker-build:
  script:
    - docker build -t ankoh/mendeleycache-server .
  tags:
    - docker
  only:
    - master

compose-local:
  type: deploy
  script:
    - docker-compose -f compose.yml -p mendeleycache stop
    - docker-compose -f compose.yml -p mendeleycache up -d
  tags:
    - privileged
  only:
    - master

github:
  script:
    - mkdir -p ~/.ssh/
    - echo "$GITHUB_DEPLOYMENT_KEY" > ~/.ssh/github.key
    - printf "Host github\n    HostName github.com\n    User git\n    IdentityFile ~/.ssh/github.key\n" >> ~/.ssh/config
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh/
    - chmod 600 ~/.ssh/config
    - chmod 600 ~/.ssh/github.key 
    - chmod 600 ~/.ssh/known_hosts
    - git push --all ssh://github/ankoh/mendeley-cache-server.git