unittest:
  script:
    - pip install --quiet -r requirements.txt
    - python -m mendeleycache.runner tests
  tags:
    - python3

sample-file-pipeline:
  script:
    - pip install --quiet -r requirements.txt
    - python -m mendeleycache.runner sample-file-pipeline
  tags:
    - python3

sample-api:
  script:
    - pip install --quiet -r requirements.txt
    - python -m mendeleycache.runner sample-api
  tags:
    - python3

