unittest:
  script:
    - pip install --quiet -r requirements.txt
    - python -m unittest discover -v
  tags:
    - python3

github:
  script:
    - mkdir -p ~/.ssh/
    - echo "$GITHUB_DEPLOYMENT_KEY" > ~/.ssh/github.key
    - printf "Host github\n    HostName github.com\n    User git\n    IdentityFile ~/.ssh/github.key\n" >> ~/.ssh/config
    - chmod 700 ~/.ssh/
    - chmod 600 ~/.ssh/config
    - chmod 600 ~/.ssh/github.key 
    - git push --all github:ankoh/mendeley-cache-server.git