unittest:
  script:
    - pip install --quiet -r requirements.txt
    - python -m mendeleycache.runner tests
  tags:
    - python3

sample-file-pipeline:
  script:
    - pip install --quiet -r requirements.txt
    - python -m mendeleycache.runner sample-pipeline
  tags:
    - python3
  only:
    - master

sample-api:
  script:
    - pip install --quiet -r requirements.txt
    - python -m mendeleycache.runner sample-api
  tags:
    - python3
  only:
    - master

docker-build:
  script:
    - docker build -t ankoh/mendeleycache-server .
  tags:
    - docker
  only:
    - master

compose-local:
  type: deploy
  script:
    - sed -e s/:app_id/$MC_APP_ID/ -e s/:app_secret/$MC_APP_SECRET/ compose.yml > derived.yml
    - docker-compose -f derived.yml -p mcserver stop
    - docker-compose -f derived.yml -p mcserver up -d
  tags:
    - privileged
  only:
    - master

github:
  script:
    - mkdir -p ~/.ssh/
    - echo "$GITHUB_DEPLOYMENT_KEY" > ~/.ssh/github.key
    - printf "Host github\n    HostName github.com\n    User git\n    IdentityFile ~/.ssh/github.key\n" >> ~/.ssh/config
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh/
    - chmod 600 ~/.ssh/config
    - chmod 600 ~/.ssh/github.key 
    - chmod 600 ~/.ssh/known_hosts
    - git push --all ssh://github/ankoh/mendeley-cache-server.git