jshint:
  script:
    - cd api
    - npm install
    - grunt jshint
  tags:
    - plain
    - node
    - grunt

mocha:
  script:
    - cd api
    - npm install
    - grunt mochaTest
  tags:
    - plain
    - node
    - grunt
