unittest:
  script:
    - pip install --quiet -r requirements.txt
    - python -m mendeleycache.runner tests
  tags:
    - python3

sample-file-pipeline:
  script:
    - pip install --quiet -r requirements.txt
    - python -m mendeleycache.runner sample-file-pipeline
  tags:
    - python3

sample-api:
  script:
    - pip install --quiet -r requirements.txt
    - python -m mendeleycache.runner sample-api
  tags:
    - python3

docker-build:
  script:
    - docker build -t ankoh/mendeleycache-server .
  tags:
    - docker
  only:
    - master
    - testing

github:
  type: deploy
  script:
    - mkdir -p ~/.ssh/
    - echo "$GITHUB_DEPLOYMENT_KEY" > ~/.ssh/github.key
    - printf "Host github\n    HostName github.com\n    User git\n    IdentityFile ~/.ssh/github.key\n" >> ~/.ssh/config
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh/
    - chmod 600 ~/.ssh/config
    - chmod 600 ~/.ssh/github.key 
    - chmod 600 ~/.ssh/known_hosts
    - git push --all ssh://github/ankoh/mendeley-cache-server.git

compose-local:
  type: deploy
  script:
    - sed -e s/:app_id/$LOCAL_APP_ID/ -e s/:app_secret/$LOCAL_APP_SECRET/ -e s/:port/32760/ -e s/:db_secret/$LOCAL_DB_SECRET/g compose.yml > derived.yml
    - docker-compose -f derived.yml -p mcserver stop
    - if $LOCAL_RESET; then docker-compose -f derived.yml -p mcserver rm -vf; fi
    - docker-compose -f derived.yml -p mcserver up -d
  tags:
    - privileged
  only:
    - master
    - testing

compose-dockerbruegge1:
  type: deploy
  script:
    - sed -i'' -e s/:app_id/$DOCKERBRUEGGE_APP_ID/ -e s/:app_secret/$DOCKERBRUEGGE_APP_SECRET/ -e s/:port/32760/ -e s/:db_secret/$DOCKERBRUEGGE_DB_SECRET/g compose.yml
    - mkdir -p ~/.ssh/
    - echo "$DOCKERBRUEGGE_DEPLOYMENT_KEY" > ~/.ssh/dockerbruegge1.key
    - printf "Host dockerbruegge1\n    HostName dockerbruegge1.informatik.tu-muenchen.de\n    User itg\n    IdentityFile ~/.ssh/dockerbruegge1.key\n" >> ~/.ssh/config
    - ssh-keyscan dockerbruegge1.informatik.tu-muenchen.de >> ~/.ssh/known_hosts
    - chmod 700 ~/.ssh/
    - chmod 600 ~/.ssh/config
    - chmod 600 ~/.ssh/dockerbruegge1.key
    - chmod 600 ~/.ssh/known_hosts
    - ssh dockerbruegge1 "mkdir -p ~/projects/mendeley-cache/server;
        rm -rf ~/projects/mendeley-cache/server;
        mkdir -p ~/projects/mendeley-cache/server;"
    - tar -czf server.tar.gz mendeleycache docker compose.yml Dockerfile
    - scp server.tar.gz dockerbruegge1:~/projects/mendeley-cache/server/
    - ssh dockerbruegge1 "tar -xzf ~/projects/mendeley-cache/server/server.tar.gz -C ~/projects/mendeley-cache/server"
    - ssh dockerbruegge1 "cd ~/projects/mendeley-cache/server; 
        docker build -t ankoh/mendeleycache-server .;
        docker-compose -f compose.yml -p mcserver stop;
        docker-compose -f compose.yml -p mcserver up -d;
        rm -rf ~/projects/mendeley-cache/server;
        docker rmi \$(docker images | grep '<none>' | awk '{print $3}') 2>/dev/null || echo 'No untagged images to delete.'"
  only:
    - master
