server:
  build: .
  restart: always
  ports:
    - "32761:8080"
  volumes:
    - "/opt/mendeley"
    - "/etc/localtime:/etc/localtime:ro"
  environment:
    - MC_CRAWLER=mendeley
    - MC_APP_ID=yourid
    - MC_APP_SECRET=yoursecret
    - MC_RESEARCH_GROUP=d0b7f41f-ad37-3b47-ab70-9feac35557cc
    - MC_DATABASE_ENGINE=sqlite
    - MC_DATABASE_PATH=/opt/mendeley/mcdb.db
    - MC_PROFILE_PAGE_PATTERN=https://www1.informatik.tu-muenchen.de/people/:firstname.:lastname
