server:
  image: ankoh/mendeleycache-server:latest
  restart: always
  ports:
    - "32760:8080"
  links:
    - "mysql:db"
  environment:
    - MC_CRAWLER=file
    - MC_DATABASE_ENGINE=mysql
    - MC_DATABASE_HOSTNAME=db
    - MC_DATABASE_PORT=3306
    - MC_DATABASE_DB=mcdb
    - MC_DATABASE_USER=root
    - MC_DATABASE_SECRET=yourrootpassword

mysqlconfig:
  build: ./docker/mysqlconfig/
  volumes:
    - "/etc/mysql/"

mysql:
  image: mysql:latest
  restart: always
  volumes_from:
    - mysqlconfig
  environment:
    - MYSQL_ROOT_PASSWORD=yourrootpassword


