# This is a sample configuration for the Mendeley cache
# Head to the website for further configuration options

mendeley:
  app_id: 231209
  app_secret: 'AlPhA4NuMeRiC20'
  research_group: 'd0b7f41f-ad37-3b47-ab70-9feac35557cc'

database:
  engine: 'sqlite'
  path: ''
