-- MySQL Script generated by MySQL Workbench
-- Thu Aug 20 23:16:18 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mendeleycache
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mendeleycache
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mendeleycache` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mendeleycache` ;

-- -----------------------------------------------------
-- Table `mendeleycache`.`cache_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mendeleycache`.`cache_profile` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `unified_name` VARCHAR(255) NOT NULL COMMENT '',
  `mendeley_profile_id` INT UNSIGNED NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `unified_name_UNIQUE` (`unified_name` ASC)  COMMENT '',
  INDEX `fk_cache_profile_mendeley_profile1_idx` (`mendeley_profile_id` ASC)  COMMENT '',
  UNIQUE INDEX `mendeley_profile_id_UNIQUE` (`mendeley_profile_id` ASC)  COMMENT '',
  CONSTRAINT `fk_cache_profile_mendeley_profile1`
    FOREIGN KEY (`mendeley_profile_id`)
    REFERENCES `mendeleycache`.`mendeley_profile` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mendeleycache`.`mendeley_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mendeleycache`.`mendeley_profile` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `cache_profile_id` INT NOT NULL COMMENT '',
  `m_id` VARCHAR(255) NOT NULL COMMENT '',
  `m_first_name` VARCHAR(35) NOT NULL COMMENT '',
  `m_last_name` VARCHAR(35) NOT NULL COMMENT '',
  `m_display_name` VARCHAR(80) NULL COMMENT '',
  `m_link` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_mendeley_profile_cache_profile1_idx` (`cache_profile_id` ASC)  COMMENT '',
  UNIQUE INDEX `m_id_UNIQUE` (`m_id` ASC)  COMMENT '',
  CONSTRAINT `fk_mendeley_profile_cache_profile1`
    FOREIGN KEY (`cache_profile_id`)
    REFERENCES `mendeleycache`.`cache_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mendeleycache`.`cache_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mendeleycache`.`cache_document` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `unified_title` VARCHAR(255) NOT NULL COMMENT '',
  `mendeley_document_id` INT UNSIGNED NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `unified_title_UNIQUE` (`unified_title` ASC)  COMMENT '',
  INDEX `fk_cache_document_mendeley_document1_idx` (`mendeley_document_id` ASC)  COMMENT '',
  UNIQUE INDEX `mendeley_document_id_UNIQUE` (`mendeley_document_id` ASC)  COMMENT '',
  CONSTRAINT `fk_cache_document_mendeley_document1`
    FOREIGN KEY (`mendeley_document_id`)
    REFERENCES `mendeleycache`.`mendeley_document` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mendeleycache`.`mendeley_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mendeleycache`.`mendeley_document` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `mendeley_profile_id` INT NOT NULL COMMENT '',
  `cache_document_id` INT NOT NULL COMMENT '',
  `m_core_id` VARCHAR(255) NULL COMMENT '',
  `m_core_title` VARCHAR(255) NULL COMMENT '',
  `m_core_type` ENUM('journal', 'book', 'generic', 'book_section', 'conference_proceedings', 'working_paper', 'report', 'web_page', 'thesis', 'magazine_article', 'statute', 'patent', 'newspaper_article', 'computer_program', 'hearing', 'television_broadcast', 'encyclopedia_article', 'case', 'film', 'bill') NULL COMMENT '',
  `m_core_created` DATETIME NULL COMMENT '',
  `m_core_last_modified` DATETIME NULL COMMENT '',
  `m_core_abstract` TEXT NULL COMMENT '',
  `m_core_source` VARCHAR(255) NULL COMMENT '',
  `m_core_year` SMALLINT NULL COMMENT '',
  `m_core_authors` TEXT NULL COMMENT '',
  `m_core_keywords` TEXT NULL COMMENT '',
  `m_tags_tags` TEXT NULL COMMENT '',
  `derived_bibtex` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_mendeley_document_cache_document1_idx` (`cache_document_id` ASC)  COMMENT '',
  INDEX `fk_mendeley_document_mendeley_profile1_idx` (`mendeley_profile_id` ASC)  COMMENT '',
  CONSTRAINT `fk_mendeley_document_cache_document1`
    FOREIGN KEY (`cache_document_id`)
    REFERENCES `mendeleycache`.`cache_document` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mendeley_document_mendeley_profile1`
    FOREIGN KEY (`mendeley_profile_id`)
    REFERENCES `mendeleycache`.`mendeley_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mendeleycache`.`cache_field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mendeleycache`.`cache_field` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(255) NOT NULL COMMENT '',
  `unified_title` VARCHAR(255) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `unified_title_UNIQUE` (`unified_title` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mendeleycache`.`cache_document_has_cache_field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mendeleycache`.`cache_document_has_cache_field` (
  `cache_document_id` INT UNSIGNED NOT NULL COMMENT '',
  `cache_field_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`cache_document_id`, `cache_field_id`)  COMMENT '',
  INDEX `fk_cache_document_has_cache_field_cache_field1_idx` (`cache_field_id` ASC)  COMMENT '',
  INDEX `fk_cache_document_has_cache_field_cache_document1_idx` (`cache_document_id` ASC)  COMMENT '',
  CONSTRAINT `fk_cache_document_has_cache_field_cache_document1`
    FOREIGN KEY (`cache_document_id`)
    REFERENCES `mendeleycache`.`cache_document` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cache_document_has_cache_field_cache_field1`
    FOREIGN KEY (`cache_field_id`)
    REFERENCES `mendeleycache`.`cache_field` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mendeleycache`.`cache_profile_has_cache_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mendeleycache`.`cache_profile_has_cache_document` (
  `cache_profile_id` INT UNSIGNED NOT NULL COMMENT '',
  `cache_document_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`cache_profile_id`, `cache_document_id`)  COMMENT '',
  INDEX `fk_cache_profile_has_cache_document_cache_document1_idx` (`cache_document_id` ASC)  COMMENT '',
  INDEX `fk_cache_profile_has_cache_document_cache_profile1_idx` (`cache_profile_id` ASC)  COMMENT '',
  CONSTRAINT `fk_cache_profile_has_cache_document_cache_profile1`
    FOREIGN KEY (`cache_profile_id`)
    REFERENCES `mendeleycache`.`cache_profile` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_cache_profile_has_cache_document_cache_document1`
    FOREIGN KEY (`cache_document_id`)
    REFERENCES `mendeleycache`.`cache_document` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mendeleycache`.`document_access_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mendeleycache`.`document_access_log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `type` ENUM('file', 'bibtex') NOT NULL DEFAULT 'file' COMMENT '',
  `date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mendeleycache`.`document_access_log_has_cache_document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mendeleycache`.`document_access_log_has_cache_document` (
  `document_access_log_id` INT NOT NULL COMMENT '',
  `cache_document_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`document_access_log_id`, `cache_document_id`)  COMMENT '',
  INDEX `fk_document_access_log_has_cache_document_cache_document1_idx` (`cache_document_id` ASC)  COMMENT '',
  INDEX `fk_document_access_log_has_cache_document_document_access_l_idx` (`document_access_log_id` ASC)  COMMENT '',
  CONSTRAINT `fk_document_access_log_has_cache_document_document_access_log1`
    FOREIGN KEY (`document_access_log_id`)
    REFERENCES `mendeleycache`.`document_access_log` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_document_access_log_has_cache_document_cache_document1`
    FOREIGN KEY (`cache_document_id`)
    REFERENCES `mendeleycache`.`cache_document` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mendeleycache`.`field_access_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mendeleycache`.`field_access_log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mendeleycache`.`field_access_log_has_cache_field`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mendeleycache`.`field_access_log_has_cache_field` (
  `field_access_log_id` INT NOT NULL COMMENT '',
  `cache_field_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`field_access_log_id`, `cache_field_id`)  COMMENT '',
  INDEX `fk_field_access_log_has_cache_field_cache_field1_idx` (`cache_field_id` ASC)  COMMENT '',
  INDEX `fk_field_access_log_has_cache_field_field_access_log1_idx` (`field_access_log_id` ASC)  COMMENT '',
  CONSTRAINT `fk_field_access_log_has_cache_field_field_access_log1`
    FOREIGN KEY (`field_access_log_id`)
    REFERENCES `mendeleycache`.`field_access_log` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_field_access_log_has_cache_field_cache_field1`
    FOREIGN KEY (`cache_field_id`)
    REFERENCES `mendeleycache`.`cache_field` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
